[theme]
base = "light"
primaryColor = "#0F766E"
backgroundColor = "#F3F7F7"
secondaryBackgroundColor = "#E9F0F0"
textColor = "#132A3A"
font = "sans-serif"

[browser]
gatherUsageStats = false

[server]
headless = true
